name: Custom Docker Build

on: 
  push:
      branches:
        - release

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            with_models=true
          tags: |
            ghcr.io/aihawk-startup/libretranslate:${{ env.GITHUB_SHA_SHORT }}
            ghcr.io/aihawk-startup/libretranslate:release